### ISSUE TITLE
file.FetchMetadata() is not working

### ISSUE THREAD

**Issue by abubelinha** [iterative/PyDrive2#103] opened 2021-04-16 15:51 UTC
I want to get many [metadata](https://developers.google.com/drive/api/v2/reference/files#resource-representations) from each file (title, mimetype, size, date last modified, ...) in just one call.

I followed [this example](https://iterative.github.io/PyDrive2/docs/build/html/filemanagement.html#handling-special-metadata) in documentation.

```
file1 = drive.CreateFile({'id': '<some file ID here>'})
print('title: %s, mimeType: %s' % (file1['title'], file1['mimeType']))

#### THE ABOVE CODE WORKS PERFECTLY

#### BUT CODE BELOW FAILS:

# (1) Fetches all basic metadata fields, including file size, last modified etc.
file1.FetchMetadata()

# (2) Fetches all metadata available.
file1.FetchMetadata(fetch_all=True)

# (3) Fetches the 'permissions' metadata field.
file1.FetchMetadata(fields='permissions')
# (4) You can update a list of specific fields like this:
file1.FetchMetadata(fields='permissions,labels,mimeType')
```

But in fact, none of the above `FetchMetadata()` example calls is working for me (under Windows 7, Python 3.8).
1, 3 & 4 return `NoneType`.

And the example 2, `FetchMetadata(fetch_all=True)`, raises this error:
```
  File "c:\python38\lib\site-packages\pydrive2\auth.py", line 84, in _decorated
    return decoratee(self, *args, **kwargs)
  File "c:\python38\lib\site-packages\pydrive2\files.py", line 467, in FetchMetadata
    raise ApiRequestError(error)
pydrive2.files.ApiRequestError: <HttpError 400 when requesting https://www.googleapis.com/drive/v2/files/1ckwZ4cwqDdjdcyB_GDvNc-T8zD4qrpKmIy2lTMQdfSU?fields=alternateLink%2CappDataContents%2CcanComment%2CcanReadRevisions%2Ccapabilitiescopyable%2CcreatedDate%2CdefaultOpenWithLink%2Cdescription%2CdownloadUrl%2Ceditable%2CembedLink%2Cetag%2CexplicitlyTrashed%2CexportLinks%2CfileExtension%2CfileSize%2CfolderColorRgb%2CfullFileExtension%2ChasAugmentedPermissions%2CheadRevisionId%2CiconLink%2Cid%2CimageMediaMetadata%2CindexableText%2CisAppAuthorized%2Ckind%2Clabels%2ClastModifyingUser%2ClastModifyingUserName%2ClastViewedByMeDate%2CmarkedViewedByMeDate%2Cmd5Checksum%2CmimeType%2CmodifiedByMeDate%2CmodifiedDate%2CopenWithLinks%2CoriginalFilename%2CownedByMe%2CownerNames%2Cowners%2Cparents%2Cpermissions%2Cproperties%2CquotaBytesUsed%2CselfLink%2Cshareable%2Cshared%2CsharedWithMeDate%2CsharingUser%2Cspaces%2CteamDriveId%2Cthumbnail%2CthumbnailLink%2Ctitle%2CtrashedDate%2CtrashingUseruserPermission%2Cversion%2CvideoMediaMetadata%2CwebContentLink%2CwebViewLink%2CwritersCanShare&supportsAllDrives=true&alt=json returned "Invalid field selection capabilitiescopyable". Details: "Invalid field selection capabilitiescopyable">
```
... and if I check that url in a browser, it is a json reply which suggests PyDrive is trying a non authenticated connection??
But of course, I have authenticated because my previous `file1['title']` and `file1['mimeType']` calls worked perfectly.

```
{
  "error": {
    "errors": [
      {
        "domain": "usageLimits",
        "reason": "dailyLimitExceededUnreg",
        "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
        "extendedHelp": "https://code.google.com/apis/console"
      }
    ],
    "code": 403,
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
  }
}
```

I wonder if this is related to #91

But in my case, I am NOT trying to update metadata.
I just want to read them.

**Comment by abubelinha** [comment] 2021-04-16 20:06
I wonder if it is related to #91 

But in my case, I am NOT trying to update metadata.
I just want to read them.

**Comment by shcheklein** [comment] 2021-04-17 01:25
> Invalid field selection capabilitiescopyable

Good catch. I've fixed and released the new version 1.8.2 -please give it a try. `file1.FetchMetadata(fetch_all=True)` should not be throwing an error. Fix is in #104 

> But in fact, none of the above FetchMetadata() example calls is working for me (under Windows 7, Python 3.8).
1, 3 & 4 return NoneType.

this is something different and most likely means that either you are using wrong credentials, trying to access a file that is public and reached its global limits, or something else is happening. I would try to use this form to execute the query and check the result:

https://developers.google.com/drive/api/v2/reference/files/get?apix_params=%7B%22fileId%22%3A%22123%22%2C%22fields%22%3A%22*%22%7D

> I wonder if this is related to #91

no, it's not . That one is about updating metadata, here is something else.

**Closed by shcheklein** 2021-04-17 01:25 UTC
Labels: bug, triage

**Comment by abubelinha** [comment] 2021-05-01 12:30
Thanks @shcheklein , I upgraded to 1.8.2, so no error when calling `file1.FetchMetadata(fecht_all=True)`

But I don't understand why you say I might be using wrong credentials.
In that case, why does `file1['title']` work a few lines above?
Both use the same credentials (same `file1` object)

BTW, I tried the [Google Explorer API form](https://developers.google.com/drive/api/v2/reference/files/get?apix_params=%7B%22fileId%22%3A%22123%22%2C%22fields%22%3A%22*%22%7D) you suggested to execute the query, and it worked perfectly (same user credentials). 

Actually, I am trying this also with public files, and `.FetchMetadata()` keeps returning `NoneType` (no matter if I give READ or EDIT public access).

So my account has access to the file, and so does the PyDrive2 `file1` object. 
I still think the problem is just inside `.FetchMetadata()` function

**Comment by shcheklein** [comment] 2021-05-01 23:36
> Thanks @shcheklein , I upgraded to 1.8.2, so no error when calling file1.FetchMetadata(fecht_all=True)

good to hear that!

> and so does the PyDrive2 file1 object

could you clarify what do you mean, please?

> I still think the problem is just inside .FetchMetadata() function

it might be. I just don't see the reason for it to fail. There are tests for this function in the repo, and it returns actual objects in those tests. We need a script to reproduce this, something that I can try to run and see that it fails.

**Comment by abubelinha** [comment] 2021-05-02 15:36
Thanks @shcheklein 
For the script, the example in my first post is not enough?

What I meant is that I don't think this is a wrong credentials issue, as you suggested.
The `file1` object HAS access to the file metadata. But only in one of two possible ways:

```
# credentials are a step before, when creating drive object
file1 = drive.CreateFile({'id': '<some file ID here>'})
# after the line above, I can use file1 in two ways, to grab the file metadata ('title', 'mimeType' ... whatever)

# this way WORKS: file1[whatever]
print('title: %s, mimeType: %s' % (file1['title'], file1['mimeType'])) 

# this way FAILS: file1.FetchMetadata() calls always return NoneType
file1.FetchMetadata(whatever) # see my first post (I called the function in 4 different ways)
```
So, what I mean is that this is not a credentials issue, because the print() line using file1['title'] produces the expected output (file name)

**Comment by shcheklein** [comment] 2021-05-03 18:01
Hmm, I see where confusion might have come from. `FetchMetadata` call doesn't itself return anything. It populates the file object with the information so that you can access it wither by doing `file1['title']` after that (w/o incurring additional API calls this time), or by `file1.metadata`.

**Comment by abubelinha** [comment] 2021-05-03 22:56
OMG ... so I completely misunderstood it.
So, you mean something like this?

```python
file1 = drive.CreateFile({'id': '<some file ID here>'})

# this would imply 3 API calls:

print(file1['title'], file1['mimeType'], file1['modifiedDate'])

# this would imply just 1 API call:

file1.FetchMetadata(fields='title,mimeType,modifiedDate,description,md5Checksum,fileSize')
print(file1['title'], file1['mimeType'], file1['modifiedDate'])
print(file1['description'], file1['md5Checksum'], file1['fileSize'])

```

**Comment by shcheklein** [comment] 2021-05-03 23:27
@abubelinha kinda, I think that `file1['title']` will be enough to fetch all basic fields (default one if you don't provide `fetchAll`). So it might happen that `mimeType` and `modifiedDate` will be part of the first call.

> file1.FetchMetadata(fields='title,mimeType,modifiedDate,description,md5Checksum,fileSize')

this should do one API call indeed
