### ISSUE TITLE
How to get the real ID of a shortcut?

### ISSUE THREAD

**Issue by hagemouse** [iterative/PyDrive2#74] opened 2021-01-02 01:15 UTC
Hi,

When someone shares something, you can make a shortcut into "My Drive", and you can access it in chrome or firefox. But the ID of the shortcut is not the real ID of the shared thing.
So how could I get the real ID from the shortcut?
I didn't find anything related with it in GoogleDriveFile.

Thank you.

**Comment by hagemouse** [comment] 2021-01-02 01:31
https://developers.google.com/drive/api/v3/shortcuts

targetID and targetMimeType not applied in pydrive2?

**Comment by shcheklein** [comment] 2021-01-02 02:52
Could you try to do `FetchMetadata` and pass `shortcutDetails` to the `fields`? 

example is here- https://iterative.github.io/PyDrive2/docs/build/html/filemanagement.html#handling-special-metadata

**Comment by hagemouse** [comment] 2021-01-02 03:48
thank you very much.

file.FetchMetadata(fields='shortcutDetails')  get nothing

file.FetchMetadata(fetch_all=True),get 403 error:
        domain | "usageLimits"
        reason | "dailyLimitExceededUnreg"
        message | "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
        extendedHelp | "https://code.google.com/apis/console"
        code | 403
        message | "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
but I have already signuped.

**Comment by shcheklein** [comment] 2021-01-02 05:36
@hagemouse hmm, what fileId do you pass to the `CreateFile`? It should be Id of the shortcut. Could you try to pass some other attributes - `mimeType`, `name`? 

`dailyLimitExceededUnreg` - is is a public file? It's a regular thing for files that are publicly shared by someone to hit those limits.

**Comment by hagemouse** [comment] 2021-01-02 16:52
Thank you for your reply.
The folder is  public shared.  I passed the id of the shortcut(a folder) , CreateFile({"id": fileId}). I tried more field , and  got the same result.
I think the error came from  FetchMetadata. If I passed a field that doesn't exist, such as FetchMetadata(field="abc"),  it will raise 403 error.  FetchMetadata(fetch_all=True) got 403 error too.

If I just use FetchMetadata() with no para, there is no field called targetId.

**Comment by hagemouse** [comment] 2021-01-02 16:59
Another problem is, it seems that there is not a function in pydrive2 than can be used to get the list of team drives.  And  I can not get the correct name(title) of team drives by FetchMetadata(driveId), all of them are same:"Team Drive".

**Comment by shcheklein** [comment] 2021-01-02 17:13
@hagemouse 

Could you try to open https://developers.google.com/drive/api/v2/reference/files/get, click "Try it" to the right and run the query, with the same ID (there is `Show standard parameters expand_more` link for the fields parameter`)

Same for the drives list - we need to see it's working in the explorer to understand what is missing.

**Comment by hagemouse** [comment] 2021-01-02 20:33
api V2 - video file

{
 "kind": "drive#file",
 "id": "1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2",
 "etag": "\"MTYwODUzONQ\"",
 "selfLink": "https://www.googleapis.com/drive/v2/files/1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2",
 "webContentLink": "https://drive.google.com/uc?id=1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2&export=download",
 "alternateLink": "https://drive.google.com/file/d/1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2/view?usp=drivesdk",
 "embedLink": "https://drive.google.com/file/d/1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2/preview?usp=drivesdk",
 "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/video/mp4",
 "thumbnailLink": "https://lh3.googleusercontent.com/Ll-ZBGeFo_-QHKVQTDqYsQd8OPLs=s220",
 "title": "1119233.mp4",
 "mimeType": "video/mp4",
 "description": "1119233.mp4",
 "labels": {
  "starred": false,
  "hidden": false,
  "trashed": false,
  "restricted": false,
  "viewed": false
 },
 "copyRequiresWriterPermission": false,
 "createdDate": "2020-12-29T00:55:43.091Z",
 "modifiedDate": "2020-12-21T08:39:21.655Z",
 "markedViewedByMeDate": "1970-01-01T00:00:00.000Z",
 "version": "7",
 "parents": [
  {
   "kind": "drive#parentReference",
   "id": "1RkJpLb084s5BK",
   "selfLink": "https://www.googleapis.com/drive/v2/files/1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2/parents/1RkJNnyrs5BK",
   "parentLink": "https://www.googleapis.com/drive/v2/files/1RkJpLb084rs5BK",
   "isRoot": false
  }
 ],
 "downloadUrl": "https://content.googleapis.com/drive/v2/files/1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2?key=AIzaSyAa8yy0xxxxxxxxxxx0vMPScDM&alt=media&source=downloadUrl",
 "userPermission": {
  "kind": "drive#permission",
  "etag": "\"Tx3mdk\"",
  "id": "me",
  "selfLink": "https://www.googleapis.com/drive/v2/files/1P2xxxxxxxxxxxxxxxxxxxxxUBiHqSQB2/permissions/me",
  "role": "organizer",
  "type": "user"
 },
 "originalFilename": "1119233.mp4",
 "fileExtension": "mp4",
 "md5Checksum": "6436bc74a8c9510f",
 "fileSize": "748050",
 "quotaBytesUsed": "0",
 "teamDriveId": "0AIpwKoXXXXXXXXPVA",
 "driveId": "0AIpwKoXXXXXXXXPVA",
 "lastModifyingUserName": "pop me",
 "lastModifyingUser": {
  "kind": "drive#user",
  "displayName": "pop me",
  "isAuthenticatedUser": false,
  "permissionId": "089867760578977"
 },
 "capabilities": {
  "canCopy": true,
  "canEdit": true
 },
 "editable": true,
 "copyable": true,
 "explicitlyTrashed": false,
 "appDataContents": false,
 "headRevisionId": "0B3Xyf1uTkHukN2gBTmxNPQ",
 "videoMediaMetadata": {
  "width": 368,
  "height": 640,
  "durationMillis": "14799"
 },
 "spaces": [
  "drive"
 ]
}

**Comment by hagemouse** [comment] 2021-01-02 20:39
api V3 - video file

{
 "kind": "drive#file",
 "id": "1P2XZxxxxxxxxxxz3k6hfdZtUBiHqSQB2",
 "name": 1119233.mp4",
 "mimeType": "video/mp4",
 "description": 1119233.mp4",
 "starred": false,
 "trashed": false,
 "explicitlyTrashed": false,
 "parents": [
  "1RkJpLb084lrRz4xLOcbxxxxxxxxxx5BK"
 ],
 "spaces": [
  "drive"
 ],
 "version": "7",
 "webContentLink": "https://drive.google.com/uc?id=1P2XZxxxxxxxxxxz3k6hfdZtUBiHqSQB2&export=download",
 "webViewLink": "https://drive.google.com/file/d/1P2XZxxxxxxxxxxz3k6hfdZtUBiHqSQB2/view?usp=drivesdk",
 "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/video/mp4",
 "hasThumbnail": true,
 "thumbnailLink": "https://lh3.googleusercontent.com/nf5FFNfp3nSnnnjjk_xbsEsS-UdW_iY96hMP40Y7s=s220",
 "thumbnailVersion": "1",
 "viewedByMe": false,
 "createdTime": "2020-12-29T00:55:43.091Z",
 "modifiedTime": "2020-12-21T08:39:21.655Z",
 "modifiedByMe": false,
 "teamDriveId": "0AIpwKxxxxxxxxxxPVA",
 "driveId": "0AIpwKxxxxxxxxxxPVA",
 "lastModifyingUser": {
  "kind": "drive#user",
  "displayName": "pop me",
  "me": false,
  "permissionId": "08986776011111178977"
 },
 "capabilities": {
  "canAddChildren": false,
  "canAddFolderFromAnotherDrive": false,
  "canChangeCopyRequiresWriterPermission": true,
  "canChangeViewersCanCopyContent": true,
  "canComment": true,
  "canCopy": true,
  "canDelete": true,
  "canDeleteChildren": false,
  "canDownload": true,
  "canEdit": true,
  "canListChildren": false,
  "canModifyContent": true,
  "canMoveChildrenOutOfTeamDrive": false,
  "canMoveChildrenOutOfDrive": false,
  "canMoveChildrenWithinTeamDrive": false,
  "canMoveChildrenWithinDrive": false,
  "canMoveItemIntoTeamDrive": true,
  "canMoveItemOutOfTeamDrive": true,
  "canMoveItemOutOfDrive": true,
  "canMoveItemWithinTeamDrive": true,
  "canMoveItemWithinDrive": true,
  "canMoveTeamDriveItem": true,
  "canReadRevisions": true,
  "canReadTeamDrive": true,
  "canReadDrive": true,
  "canRemoveChildren": false,
  "canRename": true,
  "canShare": true,
  "canTrash": true,
  "canTrashChildren": false,
  "canUntrash": true
 },
 "viewersCanCopyContent": true,
 "copyRequiresWriterPermission": false,
 "permissionIds": [
  "08986737711111118977",
  "17019612758111111118",
  "10847364028111111110",
  "13543182481111111112",
  "12656169030011111110"
 ],
 "hasAugmentedPermissions": false,
 "originalFilename": "1119233.mp4",
 "fullFileExtension": "mp4",
 "fileExtension": "mp4",
 "md5Checksum": "6436bc74a510f",
 "size": "74805",
 "quotaBytesUsed": "0",
 "headRevisionId": "0B3Xyf1uTMTN3K0tBTmxNPQ",
 "videoMediaMetadata": {
  "width": 368,
  "height": 640,
  "durationMillis": "1499"
 },
 "isAppAuthorized": false
}

**Comment by hagemouse** [comment] 2021-01-02 20:48
api V2--shortcut

{
 "kind": "drive#file",
 "id": "1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s",
 "etag": "\"MTYwNjg5MzUwOQ\"",
 "selfLink": "https://www.googleapis.com/drive/v2/files/1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s",
 "alternateLink": "https://drive.google.com/file/d/1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s/view?usp=drivesdk",
 "embedLink": "https://drive.google.com/file/d/1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s/preview?usp=drivesdk",
 "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.shortcut",
 "title": "aaaaaaaa",
 "mimeType": "application/vnd.google-apps.shortcut",
 "labels": {
  "starred": false,
  "hidden": false,
  "trashed": false,
  "restricted": false,
  "viewed": true
 },
 "copyRequiresWriterPermission": false,
 "createdDate": "2020-11-28T22:01:33.509Z",
 "modifiedDate": "2020-11-28T22:01:33.509Z",
 "modifiedByMeDate": "2020-11-28T22:01:33.509Z",
 "lastViewedByMeDate": "2020-11-28T22:01:33.509Z",
 "markedViewedByMeDate": "1970-01-01T00:00:00.000Z",
 "version": "1",
 "parents": [
  {
   "kind": "drive#parentReference",
   "id": "0AHZcyY2xxxxxxxxPVA",
   "selfLink": "https://www.googleapis.com/drive/v2/files/1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s/parents/0AHZcyY2xxxxxxxxPVA",
   "parentLink": "https://www.googleapis.com/drive/v2/files/0AHZcyY2xxxxxxxxPVA",
   "isRoot": true
  }
 ],
 "userPermission": {
  "kind": "drive#permission",
  "etag": "\"QRjKiFNq8pU6P_8wp0\"",
  "id": "me",
  "selfLink": "https://www.googleapis.com/drive/v2/files/1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s/permissions/me",
  "role": "owner",
  "type": "user"
 },
 "quotaBytesUsed": "0",
 "ownerNames": [
  "king sing"
 ],
 "owners": [
  {
   "kind": "drive#user",
   "displayName": "kin",
   "isAuthenticatedUser": true,
   "permissionId": "17019612751111111188",
   "emailAddress": "net@gmail.com"
  }
 ],
 "lastModifyingUserName": "kin",
 "lastModifyingUser": {
  "kind": "drive#user",
  "displayName": "kin",
  "isAuthenticatedUser": true,
  "permissionId": "17019612751111111188",
  "emailAddress": "net@gmail.com"
 },
 "capabilities": {
  "canCopy": true,
  "canEdit": true
 },
 "editable": true,
 "copyable": true,
 "writersCanShare": true,
 "shared": false,
 "explicitlyTrashed": false,
 "appDataContents": false,
 "spaces": [
  "drive"
 ]
}

**Comment by hagemouse** [comment] 2021-01-02 20:48
api V3 -- shortcut

**Comment by hagemouse** [comment] 2021-01-02 20:48
{
 "kind": "drive#file",
 "id": "1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s",
 "name": "aaaaaaaaaaaaa",
 "mimeType": "application/vnd.google-apps.shortcut",
 "starred": false,
 "trashed": false,
 "explicitlyTrashed": false,
 "parents": [
  "0AHZcyY2xxxxxxxxPVA"
 ],
 "spaces": [
  "drive"
 ],
 "version": "1",
 "webViewLink": "https://drive.google.com/file/d/1NOCS2V2PyaxxxxxxxxxKEzQyrrbBL5s/view?usp=drivesdk",
 "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.shortcut",
 "hasThumbnail": false,
 "thumbnailVersion": "0",
 "viewedByMe": true,
 "viewedByMeTime": "2020-11-28T22:01:33.509Z",
 "createdTime": "2020-11-28T22:01:33.509Z",
 "modifiedTime": "2020-11-28T22:01:33.509Z",
 "modifiedByMeTime": "2020-11-28T22:01:33.509Z",
 "modifiedByMe": true,
 "owners": [
  {
   "kind": "drive#user",
   "displayName": "kin",
   "me": true,
   "permissionId": "17019612751111111188",
   "emailAddress": "net@gmail.com"
  }
 ],
 "lastModifyingUser": {
  "kind": "drive#user",
  "displayName": "kin",
  "me": true,
  "permissionId": "17019612751111111188",
  "emailAddress": "net@gmail.com"
 },
 "shared": false,
 "ownedByMe": true,
 "capabilities": {
  "canAddChildren": false,
  "canAddMyDriveParent": false,
  "canChangeCopyRequiresWriterPermission": true,
  "canChangeViewersCanCopyContent": true,
  "canComment": true,
  "canCopy": true,
  "canDelete": true,
  "canDownload": false,
  "canEdit": true,
  "canListChildren": false,
  "canModifyContent": true,
  "canMoveChildrenWithinDrive": false,
  "canMoveItemIntoTeamDrive": true,
  "canMoveItemOutOfDrive": true,
  "canMoveItemWithinDrive": true,
  "canReadRevisions": true,
  "canRemoveChildren": false,
  "canRemoveMyDriveParent": false,
  "canRename": true,
  "canShare": false,
  "canTrash": true,
  "canUntrash": true
 },
 "viewersCanCopyContent": true,
 "copyRequiresWriterPermission": false,
 "writersCanShare": true,
 "quotaBytesUsed": "0",
 "isAppAuthorized": false,
 "shortcutDetails": {
  "targetId": "1pzyD0YhMVRvXhCDNCitC2SBxxxxxxxxx",
  "targetMimeType": "application/vnd.google-apps.folder"
 }
}

**Comment by hagemouse** [comment] 2021-01-02 20:53
api V2 -- Drive:

{
 "kind": "drive#file",
 "id": "0ANFKAO2IxxxxxxxxVA",
 "etag": "\"MTU5OTUyODxxxxxxxx\"",
 "selfLink": "https://www.googleapis.com/drive/v2/files/0ANFKAO2IxxxxxxxxVA",
 "alternateLink": "https://drive.google.com/drive/folders/0ANFKAO2IxxxxxxxxVA",
 "embedLink": "https://drive.google.com/embeddedfolderview?id=0ANFKAO2IxxxxxxxxVA",
 "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder",
 "title": "Drive",
 "mimeType": "application/vnd.google-apps.folder",
 "labels": {
  "starred": false,
  "hidden": false,
  "trashed": false,
  "restricted": false,
  "viewed": false
 },
 "copyRequiresWriterPermission": false,
 "createdDate": "2020-09-08T01:22:19.531Z",
 "modifiedDate": "2020-09-08T01:22:19.531Z",
 "markedViewedByMeDate": "1970-01-01T00:00:00.000Z",
 "version": "1",
 "parents": [],
 "userPermission": {
  "kind": "drive#permission",
  "etag": "\"E8oM9ss3fU3jyr4-PCnxxxxxxxx\"",
  "id": "me",
  "selfLink": "https://www.googleapis.com/drive/v2/files/0ANFKAO2IxxxxxxxxVA/permissions/me",
  "role": "organizer",
  "type": "user"
 },
 "quotaBytesUsed": "0",
 "teamDriveId": "0ANFKAO2IxxxxxxxxVA",
 "driveId": "0ANFKAO2IxxxxxxxxVA",
 "lastModifyingUserName": "kin",
 "lastModifyingUser": {
  "kind": "drive#user",
  "displayName": "kin",
  "isAuthenticatedUser": false,
  "permissionId": "09902011989411111111"
 },
 "capabilities": {
  "canCopy": true,
  "canEdit": true
 },
 "editable": true,
 "copyable": true,
 "explicitlyTrashed": false,
 "appDataContents": false,
 "spaces": [
  "drive"
 ]
}

**Comment by hagemouse** [comment] 2021-01-02 20:57
api V3 -- drive:
{
 "kind": "drive#file",
 "id": "0ANFKAO2IxxxxxxxxVA",
 "name": "Drive",
 "mimeType": "application/vnd.google-apps.folder",
 "starred": false,
 "trashed": false,
 "explicitlyTrashed": false,
 "spaces": [
  "drive"
 ],
 "version": "1",
 "webViewLink": "https://drive.google.com/drive/folders/0ANFKAO2IxxxxxxxxVA",
 "iconLink": "https://drive-thirdparty.googleusercontent.com/16/type/application/vnd.google-apps.folder",
 "hasThumbnail": false,
 "thumbnailVersion": "0",
 "viewedByMe": false,
 "createdTime": "2020-09-08T01:22:19.531Z",
 "modifiedTime": "2020-09-08T01:22:19.531Z",
 "modifiedByMe": false,
 "teamDriveId": "0ANFKAO2IxxxxxxxxVA",
 "driveId": "0ANFKAO2IxxxxxxxxVA",
 "lastModifyingUser": {
  "kind": "drive#user",
  "displayName": "kin",
  "me": false,
  "permissionId": "09902011981111111111"
 },
 "capabilities": {
  "canAddChildren": true,
  "canAddFolderFromAnotherDrive": true,
  "canChangeCopyRequiresWriterPermission": false,
  "canChangeViewersCanCopyContent": false,
  "canComment": true,
  "canCopy": true,
  "canDelete": true,
  "canDeleteChildren": true,
  "canDownload": true,
  "canEdit": true,
  "canListChildren": true,
  "canModifyContent": true,
  "canMoveChildrenOutOfTeamDrive": true,
  "canMoveChildrenOutOfDrive": true,
  "canMoveChildrenWithinTeamDrive": true,
  "canMoveChildrenWithinDrive": true,
  "canMoveItemIntoTeamDrive": true,
  "canMoveItemOutOfTeamDrive": true,
  "canMoveItemOutOfDrive": true,
  "canMoveItemWithinTeamDrive": true,
  "canMoveItemWithinDrive": true,
  "canMoveTeamDriveItem": true,
  "canReadRevisions": true,
  "canReadTeamDrive": true,
  "canReadDrive": true,
  "canRemoveChildren": true,
  "canRename": true,
  "canShare": true,
  "canTrash": true,
  "canTrashChildren": true,
  "canUntrash": true
 },
 "viewersCanCopyContent": true,
 "copyRequiresWriterPermission": false,
 "permissionIds": [
  "18889220929095999170",
  "17285802757718989575",
  "17019912758920908588",
  "09857589713938185179",
  "03989939002882899537",
  "19053807890259812399",
  "15583028090558883753",
  "11885999572919888219",
  "19827559973973079989",
  "15782577159581355239",
  "11358129037329958723",
  "00375958870018188129",
  "12709231139819888095",
  "11310823305801599938",
  "02291339531912571987",
  "17235111880893871128",
  "00089825982380331901",
  "00950992129809928058",
  "11387590119890808989",
  "05198210577211973500",
  "00800718019983090305",
  "09835810883988391091"
 ],
 "hasAugmentedPermissions": false,
 "quotaBytesUsed": "0",
 "isAppAuthorized": false
}

**Comment by hagemouse** [comment] 2021-01-02 21:04
from v2 to v3:
1. title -> name
2. "parents" type changed to list
3. added "shortcutDetails"
4. extended "capabilities"
5. reduce many  fields

can not get team drive list or names from files.get.  have to use drives.get.  but I did not find it  in pydrive2.

**Comment by shcheklein** [comment] 2021-01-02 22:33
For `shortcutDetails`, I can't reproduce this. Even V2 explorer gives me details. If you item is located on a team drive, could you try to set `supportsAllDrives` `true`?

<img width="1436" alt="Screen Shot 2021-01-02 at 2 30 28 PM" src="https://user-images.githubusercontent.com/3659196/103467766-2ffaaf80-4d07-11eb-81d6-392fe2554a4d.png">
<img width="1440" alt="Screen Shot 2021-01-02 at 2 30 42 PM" src="https://user-images.githubusercontent.com/3659196/103467767-338e3680-4d07-11eb-9064-9dd80b8e871b.png">

> can not get team drive list or names from files.get. have to use drives.get. but I did not find it in pydrive2.

what are you trying to do here? why do you need a list of all drives?

**Comment by hagemouse** [comment] 2021-01-03 00:18
When have a fileId ,I want to make a full path like this: /gdrive/Shareddrives/a/b/c/1.zip.  But now I think I can write the ids and name  of my team drives as a tuple.

Thank you very much.

**Comment by shcheklein** [comment] 2021-01-03 19:28
so, does it mean the problem is solved? I'm closing the issue then, feel free to reopen if needed.

**Closed by shcheklein** 2021-01-03 19:28 UTC
Labels: question
